#include "web_control.h"
#include <Preferences.h>
namespace { Preferences prefs;
String esc(const char *s){ String o; while(*s){char c=*s++;if(c=='"'||c=='\\')o+='\\';if(uint8_t(c)>=32)o+=c;}return o;}
const char PAGE[] PROGMEM=R"HTML(<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Monster Eyes</title><style>body{font:16px system-ui;max-width:42rem;margin:auto;padding:1rem;background:#10091a;color:white}section{background:#241634;padding:1rem;margin:.8rem 0;border-radius:.8rem}button,select,input{font:inherit;padding:.65rem;margin:.25rem;border:0;border-radius:.4rem}button{background:#7851a9;color:white}.wide{width:100%}.grid{display:grid;grid-template-columns:1fr 1fr;gap:.5rem}</style></head><body><h1>Monster Eyes</h1><section id=status>Connecting…</section><section><select id=style class=wide></select><div class=grid><button onclick="post('/api/style/previous')">Previous</button><button onclick="post('/api/style/next')">Next</button></div></section><section><button id=cycle onclick=toggleCycle()>Enable cycle</button><input id=interval type=number min=5 max=3600 value=30><button onclick=saveCycle()>Apply interval</button></section><section><h2>Enabled eyes</h2><div id=eyes></div></section><section id=setup hidden><h2>Wi-Fi setup</h2><form method=post action=/provision><input name=ssid placeholder="Network name" required class=wide><input name=password type=password placeholder=Password class=wide><button type=submit>Connect and save</button></form></section><script>const q=x=>document.getElementById(x);let s={};async function post(u,d={}){await fetch(u,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(d)});refresh()}async function refresh(){try{s=await(await fetch('/api/status')).json();q('status').innerHTML=`<b>${s.styleName}</b><br>Battery: ${s.batteryPercent===null?'Unavailable':s.batteryPercent+'%'}<br>Wi-Fi: ${s.wifi} ${s.ip||''}`;q('style').innerHTML=s.styles.map((x,i)=>s.enabled[i]?`<option value=${i}>${x}</option>`:'').join('');q('style').value=s.style;q('style').onchange=()=>post('/api/style',{style:q('style').value});q('eyes').innerHTML=s.styles.map((x,i)=>`<label style="display:block"><input type=checkbox ${s.enabled[i]?'checked':''} onchange="post('/api/eyes/enabled',{style:${i},enabled:this.checked})"> ${x}</label>`).join('');q('cycle').textContent=s.cycle?'Disable cycle':'Enable cycle';q('interval').value=s.interval;q('setup').hidden=!s.provisioning}catch(e){q('status').textContent='Device unavailable'}}function toggleCycle(){post('/api/cycle',{enabled:!s.cycle,interval:q('interval').value})}function saveCycle(){post('/api/cycle',{enabled:s.cycle,interval:q('interval').value})}refresh();setInterval(refresh,2500)</script></body></html>)HTML";
}
void WebControl::begin(bool force){uint64_t m=ESP.getEfuseMac();char x[7];snprintf(x,sizeof(x),"%06llX",(unsigned long long)(m&0xffffff));_apName="MonsterEyes-"+String(x);_apPassword="eyes-"+String(x);WiFi.setHostname(_apName.c_str());prefs.begin("monster-web",true);_cycle=prefs.getBool("cycle",false);_interval=constrain(prefs.getUInt("interval",30000),5000UL,3600000UL);prefs.end();_nextCycle=millis()+_interval;if(force)startProvisioning();else connectSaved();}
void WebControl::connectSaved(){prefs.begin("monster-wifi",true);String s=prefs.getString("ssid"),p=prefs.getString("password");prefs.end();_configured=s.length();if(!_configured){startProvisioning();return;}WiFi.mode(WIFI_STA);WiFi.begin(s.c_str(),p.c_str());p="";_connectStarted=millis();startServer();}
void WebControl::startProvisioning(){if(_provisioning)return;_provisioning=true;WiFi.mode(WIFI_AP_STA);WiFi.softAP(_apName.c_str(),_apPassword.c_str());_dns.start(53,"*",WiFi.softAPIP());Serial.printf("Wi-Fi setup: %s password %s http://%s/\n",_apName.c_str(),_apPassword.c_str(),WiFi.softAPIP().toString().c_str());startServer();}
void WebControl::startServer(){if(_started)return;_server.on("/",HTTP_GET,[this]{_server.send_P(200,"text/html; charset=utf-8",PAGE);});_server.on("/api/status",HTTP_GET,[this]{_server.send(200,"application/json",statusJson());});_server.on("/api/style",HTTP_POST,[this]{if(_server.hasArg("style")){_eyes.setStyle(_server.arg("style").toInt());manualStyleSelected();}_server.send(204);});_server.on("/api/style/next",HTTP_POST,[this]{_eyes.nextStyle();manualStyleSelected();_server.send(204);});_server.on("/api/style/previous",HTTP_POST,[this]{_eyes.previousStyle();manualStyleSelected();_server.send(204);});_server.on("/api/eyes/enabled",HTTP_POST,[this]{if(!_server.hasArg("style")||!_server.hasArg("enabled")){_server.send(400);return;}bool ok=_eyes.setStyleEnabled(_server.arg("style").toInt(),_server.arg("enabled")=="true"||_server.arg("enabled")=="1");_server.send(ok?204:409);});_server.on("/api/cycle",HTTP_POST,[this]{if(_server.hasArg("interval"))_interval=constrain(_server.arg("interval").toInt(),5,3600)*1000UL;if(_server.hasArg("enabled"))_cycle=_server.arg("enabled")=="true"||_server.arg("enabled")=="1";_nextCycle=millis()+_interval;prefs.begin("monster-web",false);prefs.putBool("cycle",_cycle);prefs.putUInt("interval",_interval);prefs.end();_server.send(204);});_server.on("/provision",HTTP_POST,[this]{handleProvision();});_server.onNotFound([this]{_server.sendHeader("Location","/",true);_server.send(302);});_server.begin();_started=true;}
void WebControl::handleProvision(){if(!_provisioning||!_server.hasArg("ssid")){_server.send(403);return;}prefs.begin("monster-wifi",false);prefs.putString("ssid",_server.arg("ssid"));prefs.putString("password",_server.arg("password"));prefs.end();_server.send(200,"text/html","Credentials saved. Rebooting…");delay(500);ESP.restart();}
String WebControl::statusJson()const{String o="{\"mode\":\""+String(_cycle?"Cycle":"Manual")+"\",\"style\":"+String(_eyes.style())+",\"styleName\":\""+esc(_eyes.styleName(_eyes.style()))+"\",\"styleCount\":"+String(_eyes.styleCount())+",\"batteryPercent\":"+(_battery<0?String("null"):String(_battery))+",\"externalPower\":\"unknown\",\"cycle\":"+(_cycle?"true":"false")+",\"interval\":"+String(_interval/1000)+",\"wifi\":\""+(connected()?"connected":(_provisioning?"provisioning":"connecting"))+"\",\"ip\":\""+(connected()?WiFi.localIP().toString():WiFi.softAPIP().toString())+"\",\"configured\":"+(_configured?"true":"false")+",\"provisioning\":"+(_provisioning?"true":"false")+",\"styles\":[";for(uint8_t i=0;i<_eyes.styleCount();++i){if(i)o+=',';o+='"'+esc(_eyes.styleName(i))+'"';}o+="],\"enabled\":[";for(uint8_t i=0;i<_eyes.styleCount();++i){if(i)o+=',';o+=_eyes.styleEnabled(i)?"true":"false";}return o+"]}";}
void WebControl::manualStyleSelected(){_cycle=false;_nextCycle=0;prefs.begin("monster-web",false);prefs.putBool("cycle",false);prefs.end();}
void WebControl::handleSerial(){while(Serial.available()){char c=Serial.read();if(c=='\r')continue;if(c!='\n'&&_serialLine.length()<96){_serialLine+=c;continue;}_serialLine.trim();if(_serialLine=="wifi status")Serial.printf("wifi=%s ip=%s provisioning=%s\n",connected()?"connected":"disconnected",(connected()?WiFi.localIP():WiFi.softAPIP()).toString().c_str(),_provisioning?"yes":"no");else if(_serialLine=="wifi provision")startProvisioning();else if(_serialLine=="wifi reconnect")WiFi.reconnect();else if(_serialLine=="wifi clear")Serial.println("Type: confirm wifi clear");else if(_serialLine=="confirm wifi clear"){prefs.begin("monster-wifi",false);prefs.clear();prefs.end();ESP.restart();}else if(_serialLine=="next")_eyes.nextStyle();else if(_serialLine=="previous")_eyes.previousStyle();_serialLine="";}}
void WebControl::update(uint32_t now){handleSerial();_server.handleClient();if(_provisioning)_dns.processNextRequest();if(!_provisioning&&!connected()&&now-_connectStarted>15000)startProvisioning();if(_cycle&&int32_t(now-_nextCycle)>=0){_eyes.nextStyle();_nextCycle=now+_interval;}}
void WebControl::stop(){_dns.stop();_server.stop();WiFi.disconnect(true);WiFi.mode(WIFI_OFF);}
